packages:
  - 'packages/*'

overrides:
  '@qnx/errors': 'workspace:*'
  '@qnx/response': 'workspace:*'
  '@qnx/crypto': 'workspace:*'
  '@qnx/winston': 'workspace:*'
  '@qnx/log': 'workspace:*'
  '@qnx/message': 'workspace:*'
  '@qnx/interfaces': 'workspace:*'
  '@qnx/core-helpers': 'workspace:*'
  '@qnx/client': 'workspace:*'
  '@qnx/mcp': 'workspace:*'

minimumReleaseAgeExclude:
  - '@types/node@25.9.1'
  - '@vitest/coverage-v8@4.1.7'
  - '@vitest/expect@4.1.7'
  - '@vitest/mocker@4.1.7'
  - '@vitest/pretty-format@4.1.7'
  - '@vitest/runner@4.1.7'
  - '@vitest/snapshot@4.1.7'
  - '@vitest/spy@4.1.7'
  - '@vitest/ui@4.1.7'
  - '@vitest/utils@4.1.7'
  - vitest@4.1.7

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  less: true
  nx: true
  unrs-resolver: true
