name: Publish Package

on:
  push:
    tags:
      - v*

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [18.x]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/

      - name: Pnpm Install
        run: pnpm install

      - name: Branch Track
        run: git branch --track main origin/main

      - name: Unit Test
        run: pnpm affected:test -t --base=origin/main

      - name: App Test
        run: pnpm app:test --base=origin/main

      - name: Build
        run: pnpm affected:build -t --base=origin/main

      - run: pnpm affected:publish -t --base=origin/main
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NODE_OPTIONS: '--max-old-space-size=6144'
