name: Publish Package

on:
  push:
    branches:
      - next
    tags:
      - v*

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [20.x]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/

      - name: Pnpm Install
        run: pnpm install

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      - name: Unit Test
        run: pnpm affected:test

      - name: App Test
        run: pnpm app:test

      - name: Build
        run: pnpm affected:build

      - run: pnpm affected:publish next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NODE_OPTIONS: '--max-old-space-size=6144'
